import { toRgbTuple } from "./scripts/utils/css-rgb-tuple.mjs";

/**
 * Style Dictionary config for @jigsaw/theme-default (CSS only).
 *
 * Selectors match the previous @jigsaw/tokens default theme outputs:
 * - base.css → :root
 * - semantic-light.css → :root, [data-theme='light']
 * - semantic-dark.css → [data-theme='dark'], .dark
 */

const cssThemedVariables = ({ dictionary, options }) => {
  const selector = options.selector ?? ":root";
  const header = options.showFileHeader
    ? `/**\n * Generated by Style Dictionary — do not edit directly.\n */\n`
    : "";

  const lines = dictionary.allTokens.map((token) => {
    const path = options.stripFirstSegment ? token.path.slice(1) : token.path;
    return `  --${path.join("-")}: ${toRgbTuple(token.value)};`;
  });

  return `${header}${selector} {\n${lines.join("\n")}\n}\n`;
};

const cssPlatform = (files) => ({
  transformGroup: "css",
  buildPath: "dist/css/",
  files: files.map(({ destination, filter, options }) => ({
    destination,
    format: "css/themed-variables",
    filter,
    options,
  })),
});

export default {
  source: ["src/**/*.json"],
  platforms: {
    cssBase: cssPlatform([
      {
        destination: "base.css",
        filter: (token) => token.filePath.includes("/base/"),
        options: {
          selector: ":root",
          stripFirstSegment: false,
          showFileHeader: true,
        },
      },
    ]),
    cssLight: cssPlatform([
      {
        destination: "semantic-light.css",
        filter: (token) => token.path[0] === "light",
        options: {
          selector: ":root, [data-theme='light']",
          stripFirstSegment: true,
          showFileHeader: true,
        },
      },
    ]),
    cssDark: cssPlatform([
      {
        destination: "semantic-dark.css",
        filter: (token) => token.path[0] === "dark",
        options: {
          selector: "[data-theme='dark'], .dark",
          stripFirstSegment: true,
          showFileHeader: true,
        },
      },
    ]),
  },
  hooks: {
    formats: {
      "css/themed-variables": cssThemedVariables,
    },
  },
};
