/**
 * Storybook/docs-only token export (nested JSON values).
 * Not for Tailwind configuration — use tailwind-theme.css for that.
 */
export const docsTokens = ({ dictionary, options }) => {
  const tokens = {};
  for (const token of dictionary.allTokens) {
    let obj = tokens;
    for (let i = 0; i < token.path.length - 1; i++) {
      const key = token.path[i];
      if (!Object.prototype.hasOwnProperty.call(obj, key)) obj[key] = {};
      obj = obj[key];
    }
    obj[token.path[token.path.length - 1]] = token.value;
  }

  const header = options?.showFileHeader
    ? `/**\n * Design token values for Storybook documentation\n * Generated by Style Dictionary — do not edit directly.\n */\n`
    : "";

  return `${header}export default ${JSON.stringify(tokens, null, 2)};\n`;
};
