/**
 * Convert a CSS color value to a space-separated RGB tuple
 * (e.g. "#ff6b1a" → "255 107 26") so Tailwind's `<alpha-value>`
 * placeholder pattern can apply opacity modifiers like `/20`.
 */
function toRgbTuple(value) {
  if (typeof value !== "string") return value;
  const v = value.trim().toLowerCase();
  if (v === "transparent") return "0 0 0";
  const short = v.match(/^#([0-9a-f])([0-9a-f])([0-9a-f])$/);
  if (short) {
    const [, r, g, b] = short;
    return `${parseInt(r + r, 16)} ${parseInt(g + g, 16)} ${parseInt(b + b, 16)}`;
  }
  const long = v.match(/^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/);
  if (long) {
    const [, r, g, b] = long;
    return `${parseInt(r, 16)} ${parseInt(g, 16)} ${parseInt(b, 16)}`;
  }
  return value;
}

/**
 * CSS variables format. Pass `stripFirstSegment: true` for semantic files
 * so "light"/"dark"/"portfolio" is removed from the variable name.
 */
function cssThemedVariables({ dictionary, options }) {
  const selector = options.selector ?? ":root";
  const header = options.showFileHeader
    ? `/**\n * Generated by Style Dictionary — do not edit directly.\n */\n`
    : "";

  const lines = dictionary.allTokens.map((token) => {
    const path = options.stripFirstSegment ? token.path.slice(1) : token.path;
    return `  --${path.join("-")}: ${toRgbTuple(token.value)};`;
  });

  return `${header}${selector} {\n${lines.join("\n")}\n}\n`;
}

/** Tailwind theme.mjs format */
function tailwindTheme({ dictionary }) {
  const theme = {};
  for (const token of dictionary.allTokens) {
    let obj = theme;
    for (let i = 0; i < token.path.length - 1; i++) {
      const key = token.path[i];
      if (!Object.prototype.hasOwnProperty.call(obj, key)) obj[key] = {};
      obj = obj[key];
    }
    obj[token.path[token.path.length - 1]] = token.value;
  }
  return `/**
 * Design tokens for Tailwind theme.extend
 * Generated by Style Dictionary — do not edit directly.
 */
export default ${JSON.stringify(theme, null, 2)};\n`;
}

// ─── Shared config (spacing, typography, motion, radius, shadows) ───────────
const sharedConfig = {
  source: ["src/tokens/shared/**/*.json"],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "shared/base.css",
          format: "css/themed-variables",
          options: { selector: ":root", stripFirstSegment: false, showFileHeader: true },
        },
      ],
    },
    js: {
      transformGroup: "js",
      buildPath: "dist/",
      files: [
        {
          destination: "theme.mjs",
          format: "tailwind/theme",
          options: { showFileHeader: true },
        },
      ],
    },
  },
  hooks: { formats: { "css/themed-variables": cssThemedVariables, "tailwind/theme": tailwindTheme } },
};

// ─── Default theme (neutral palette + light/dark semantic) ──────────────────
const defaultThemeConfig = {
  source: [
    "src/tokens/themes/default/base/**/*.json",
    "src/tokens/themes/default/semantic/**/*.json",
  ],
  platforms: {
    cssBase: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "themes/default/base.css",
          format: "css/themed-variables",
          filter: (token) => token.filePath.includes("default/base"),
          options: { selector: ":root", stripFirstSegment: false, showFileHeader: true },
        },
      ],
    },
    cssLight: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "themes/default/semantic-light.css",
          format: "css/themed-variables",
          filter: (token) => token.path[0] === "light",
          options: {
            selector: ":root, [data-theme='light']",
            stripFirstSegment: true,
            showFileHeader: true,
          },
        },
      ],
    },
    cssDark: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "themes/default/semantic-dark.css",
          format: "css/themed-variables",
          filter: (token) => token.path[0] === "dark",
          options: {
            selector: "[data-theme='dark'], .dark",
            stripFirstSegment: true,
            showFileHeader: true,
          },
        },
      ],
    },
  },
  hooks: { formats: { "css/themed-variables": cssThemedVariables } },
};

// ─── Portfolio theme (navy/orange palette + dark semantic) ──────────────────
const portfolioThemeConfig = {
  source: [
    "src/tokens/themes/portfolio/base/**/*.json",
    "src/tokens/themes/portfolio/semantic/**/*.json",
  ],
  platforms: {
    cssBase: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "themes/portfolio/base.css",
          format: "css/themed-variables",
          filter: (token) => token.filePath.includes("portfolio/base"),
          options: {
            selector: "[data-theme='portfolio']",
            stripFirstSegment: false,
            showFileHeader: true,
          },
        },
      ],
    },
    cssSemantic: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "themes/portfolio/semantic.css",
          format: "css/themed-variables",
          filter: (token) => token.path[0] === "portfolio",
          options: {
            selector: "[data-theme='portfolio']",
            stripFirstSegment: true,
            showFileHeader: true,
          },
        },
      ],
    },
  },
  hooks: { formats: { "css/themed-variables": cssThemedVariables } },
};

// Style Dictionary supports exporting an array of configs
export default [sharedConfig, defaultThemeConfig, portfolioThemeConfig];
