/**
 * Convert a CSS color value to a space-separated RGB tuple
 * (e.g. "#ff6b1a" → "255 107 26") so Tailwind's `<alpha-value>`
 * placeholder pattern can apply opacity modifiers like `/20`.
 *
 * - Hex (#rgb, #rrggbb) → "r g b"
 * - "transparent" → "0 0 0" (alpha modifier becomes a no-op, fine for our use)
 * - Anything else is returned unchanged.
 */
function toRgbTuple(value) {
  if (typeof value !== "string") return value;
  const v = value.trim().toLowerCase();
  if (v === "transparent") return "0 0 0";
  const short = v.match(/^#([0-9a-f])([0-9a-f])([0-9a-f])$/);
  if (short) {
    const [, r, g, b] = short;
    return `${parseInt(r + r, 16)} ${parseInt(g + g, 16)} ${parseInt(b + b, 16)}`;
  }
  const long = v.match(/^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/);
  if (long) {
    const [, r, g, b] = long;
    return `${parseInt(r, 16)} ${parseInt(g, 16)} ${parseInt(b, 16)}`;
  }
  return value;
}

/**
 * Custom CSS variables format that strips a leading theme path segment
 * (e.g. "light" or "dark") so both themes produce the same variable names,
 * and emits colors as RGB tuples for Tailwind `<alpha-value>` support.
 */
function cssThemedVariables({ dictionary, options }) {
  const selector = options.selector ?? ":root";
  const header = options.showFileHeader
    ? `/**\n * Generated by Style Dictionary — do not edit directly.\n */\n`
    : "";

  const lines = dictionary.allTokens.map((token) => {
    // token.path looks like ["light", "color", "surface", "primary"]
    // Strip the first segment (theme) so var name is --color-surface-primary
    const path = token.path.slice(1);
    return `  --${path.join("-")}: ${toRgbTuple(token.value)};`;
  });

  return `${header}${selector} {\n${lines.join("\n")}\n}\n`;
}

/** @type {import('style-dictionary').Config} */
export default {
  source: ["src/tokens/**/*.json"],
  platforms: {
    // Base CSS variables (palette, spacing, typography, etc.) in :root
    css: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "base.css",
          format: "css/variables",
          filter: (token) => token.filePath.includes("/base/"),
          options: {
            selector: ":root",
            showFileHeader: true,
          },
        },
      ],
    },
    // Light theme semantic variables
    cssLight: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "semantic-light.css",
          format: "css/themed-variables",
          filter: (token) => token.path[0] === "light",
          options: {
            selector: ":root, [data-theme='light']",
            showFileHeader: true,
          },
        },
      ],
    },
    // Dark theme semantic variables
    cssDark: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "semantic-dark.css",
          format: "css/themed-variables",
          filter: (token) => token.path[0] === "dark",
          options: {
            selector: "[data-theme='dark'], .dark",
            showFileHeader: true,
          },
        },
      ],
    },
    // Tailwind theme object from base tokens only
    js: {
      transformGroup: "js",
      buildPath: "dist/",
      files: [
        {
          destination: "theme.mjs",
          format: "tailwind/theme",
          filter: (token) => token.filePath.includes("/base/"),
          options: { showFileHeader: true },
        },
      ],
    },
  },
  hooks: {
    formats: {
      "css/themed-variables": cssThemedVariables,
      "tailwind/theme": ({ dictionary }) => {
        const theme = {};
        for (const token of dictionary.allTokens) {
          let obj = theme;
          const path = token.path;
          for (let i = 0; i < path.length - 1; i++) {
            const key = path[i];
            if (!Object.prototype.hasOwnProperty.call(obj, key)) obj[key] = {};
            obj = obj[key];
          }
          obj[path[path.length - 1]] = token.value;
        }
        const header = `/**
 * Design tokens for Tailwind theme.extend
 * Generated by Style Dictionary — do not edit directly.
 */
`;
        return header + "export default " + JSON.stringify(theme, null, 2) + ";\n";
      },
    },
  },
};
