import { cssHooks, cssPlatform } from "@jigsaw/theme-build";
import {
  baseCssSelector,
  capitalize,
  discoverFigmaThemes,
  discoverSemanticModes,
  discoverThemes,
  isThemeBaseToken,
  figmaTokens,
  FIGMA_OUTPUT_DIR,
  isStandaloneSemantic,
  mergeFigmaBaseAndSemantic,
  semanticCssSelector,
  sortAppearanceModes,
  splitSemanticByMode,
  themeBaseSourceGlob,
  themeHasBase,
  themeSemanticSourceGlob,
  themeSourceGlob,
} from "./scripts/index.mjs";
import { tailwindThemeCss } from "./scripts/formats/tailwind-theme-css/index.mjs";
import { tailwindColorVarRef } from "./scripts/utils/tailwind-theme-color.mjs";

/** Tailwind theme.mjs format */
const tailwindTheme = ({ dictionary }) => {
  const theme = {};
  for (const token of dictionary.allTokens) {
    let obj = theme;
    for (let i = 0; i < token.path.length - 1; i++) {
      const key = token.path[i];
      if (!Object.prototype.hasOwnProperty.call(obj, key)) obj[key] = {};
      obj = obj[key];
    }
    const value =
      token.path[0] === "color" ? tailwindColorVarRef(token.path) : token.value;
    obj[token.path[token.path.length - 1]] = value;
  }
  return `/**
 * Design tokens for Tailwind theme.extend
 * Generated by Style Dictionary — do not edit directly.
 */
export default ${JSON.stringify(theme, null, 2)};\n`;
};

const figmaFormats = { "figma/tokens": figmaTokens };

const CSS_BUILD_PATH = "dist/css/";
const FIGMA_BUILD_PATH = `${FIGMA_OUTPUT_DIR}/`;

/** @param {Array<{ destination: string, filter?: (token: object) => boolean, options?: object }>} files */
const figmaPlatform = (files) => ({
  buildPath: FIGMA_BUILD_PATH,
  log: { warnings: "disabled" },
  files: files.map(({ destination, filter, options }) => ({
    destination,
    format: "figma/tokens",
    ...(filter ? { filter } : {}),
    ...(options ? { options } : {}),
  })),
});

/** @param {string[]} source @param {Record<string, object>} platforms @param {object} hooks */
const sdConfig = (source, platforms, hooks) => ({ source, platforms, hooks });

// ─── Theme CSS — discovered from src/tokens/themes/{id}/ ────────────────────

const buildThemeCssConfig = (themeId) => {
  const modes = discoverSemanticModes(themeId);
  const hasBase = themeHasBase(themeId);
  const hasSemantic = modes.length > 0;
  if (!hasBase && !hasSemantic) return null;

  const platforms = {};

  if (hasBase) {
    platforms.cssBase = cssPlatform(
      [
        {
          destination: `themes/${themeId}/base.css`,
          filter: (token) => isThemeBaseToken(themeId, token),
          options: {
            selector: baseCssSelector(themeId),
            stripFirstSegment: false,
            showFileHeader: true,
          },
        },
      ],
      CSS_BUILD_PATH,
    );
  }

  if (hasSemantic) {
    if (splitSemanticByMode(themeId, modes)) {
      for (const mode of modes) {
        platforms[`css${capitalize(mode)}`] = cssPlatform(
          [
            {
              destination: `themes/${themeId}/semantic-${mode}.css`,
              filter: (token) => token.path[0] === mode,
              options: {
                selector: semanticCssSelector(themeId, mode),
                stripFirstSegment: true,
                showFileHeader: true,
              },
            },
          ],
          CSS_BUILD_PATH,
        );
      }
    } else {
      const mode = modes[0];
      platforms.cssSemantic = cssPlatform(
        [
          {
            destination: `themes/${themeId}/semantic.css`,
            filter: (token) => token.path[0] === mode,
            options: {
              selector: semanticCssSelector(themeId, mode),
              stripFirstSegment: true,
              showFileHeader: true,
            },
          },
        ],
        CSS_BUILD_PATH,
      );
    }
  }

  return sdConfig([themeSourceGlob(themeId)], platforms, cssHooks);
};

// ─── Figma / Tokens Studio exports (legacy value/type JSON) ─────────────────
// No transformGroup: css/js transforms mutate values (e.g. hex → RGB tuples).
// Figma exports read token.original via figma/tokens for source literals.
//
// log.warnings disabled: SD flags leaf-key name collisions on flat token.name —
// benign; we nest by full path. Output files follow {slug}.tokens.json convention.
// $themes.json for Tokens Studio sync → JSW-56 (allowlisted in verify script).

// Output filenames must match discoverFigmaOutputs() in scripts/figma/discovery/discover-outputs/discover-outputs.mjs.

const buildThemeFigmaConfig = (themeId) => {
  const modes = discoverSemanticModes(themeId);
  const hasBase = themeHasBase(themeId);
  const hasSemantic = modes.length > 0;
  if (!hasBase && !hasSemantic) return null;

  if (mergeFigmaBaseAndSemantic(themeId, modes)) {
    return sdConfig(
      [themeBaseSourceGlob(themeId), themeSemanticSourceGlob(themeId)],
      {
        figma: figmaPlatform([
          {
            destination: `${themeId}.tokens.json`,
            filter: (token) =>
              isThemeBaseToken(themeId, token) || token.path[0] === themeId,
            options: { stripModePrefixes: [themeId] },
          },
        ]),
      },
      { formats: figmaFormats },
    );
  }

  const source = [];
  const platforms = {};

  if (hasBase) {
    source.push(themeBaseSourceGlob(themeId));
    platforms.figmaBase = figmaPlatform([
      {
        destination: `${themeId}-base.tokens.json`,
        filter: (token) => isThemeBaseToken(themeId, token),
      },
    ]);
  }

  if (hasSemantic && splitSemanticByMode(themeId, modes)) {
    source.push(themeSemanticSourceGlob(themeId));
    for (const mode of sortAppearanceModes(modes)) {
      platforms[`figma${capitalize(mode)}`] = figmaPlatform([
        {
          destination: `${themeId}-${mode}.tokens.json`,
          filter: (token) => token.path[0] === mode,
          options: { stripFirstSegment: true },
        },
      ]);
    }
  } else if (hasSemantic && isStandaloneSemantic(themeId, modes)) {
    const mode = modes[0];
    source.push(themeSemanticSourceGlob(themeId));
    platforms.figmaSemantic = figmaPlatform([
      {
        destination: `${themeId}-semantic.tokens.json`,
        filter: (token) => token.path[0] === mode,
        options: { stripFirstSegment: true },
      },
    ]);
  }

  if (source.length === 0) return null;

  return sdConfig(source, platforms, { formats: figmaFormats });
};

// ─── Shared + Tailwind (fixed entry points) ───────────────────────────────────

const sharedConfig = sdConfig(
  ["src/tokens/shared/**/*.json"],
  {
    css: cssPlatform(
      [
        {
          destination: "shared/base.css",
          filter: () => true,
          options: { selector: ":root", stripFirstSegment: false, showFileHeader: true },
        },
      ],
      CSS_BUILD_PATH,
    ),
  },
  cssHooks,
);

const tailwindThemeConfig = sdConfig(
  ["src/tokens/shared/**/*.json", "src/tokens/color-schema/**/*.json"],
  {
    js: {
      transformGroup: "js",
      buildPath: "dist/",
      files: [
        {
          destination: "theme.mjs",
          format: "tailwind/theme",
          options: { showFileHeader: true },
        },
      ],
    },
    tailwindCss: {
      transformGroup: "js",
      buildPath: CSS_BUILD_PATH,
      files: [
        {
          destination: "tailwind-theme.css",
          format: "tailwind/theme-css",
          options: { showFileHeader: true },
        },
      ],
    },
  },
  {
    formats: {
      "tailwind/theme": tailwindTheme,
      "tailwind/theme-css": tailwindThemeCss,
    },
  },
);

const figmaSharedConfig = sdConfig(
  ["src/tokens/shared/**/*.json"],
  { figma: figmaPlatform([{ destination: "shared.tokens.json" }]) },
  { formats: figmaFormats },
);

const themeCssConfigs = discoverThemes()
  .map((themeId) => buildThemeCssConfig(themeId))
  .filter(Boolean);

const themeFigmaConfigs = discoverFigmaThemes()
  .map((themeId) => buildThemeFigmaConfig(themeId))
  .filter(Boolean);

export default [
  sharedConfig,
  tailwindThemeConfig,
  ...themeCssConfigs,
  figmaSharedConfig,
  ...themeFigmaConfigs,
];
